### ISSUE TITLE
Consistent License naming

### ISSUE THREAD

**Issue by HipyCas** [The-Noah/lsfp#27]
**Is your feature request related to a problem? Please describe.**
While adding new licenses, I did not really know how to properly name them. I can see many variants in the license names:

```rust
pub const LICENSES: &[(&str, &str)] = &[
  ("MIT", "MIT License"),  // License short name uppercase, license capitalized-lowercase
  ("GPLv3", "GNU GENERAL PUBLIC LICENSE\nVersion 3"),  // All uppercase except version, separated by newline. In short name, version with 'v' prefix
  [...]
  ("Mozilla Public License 2.0", "Mozilla Public License Version 2.0"),  // All capitalized-lowercase, version separated by space. In short name, the version is shown as a floating-point number. Long name only adds "Version" to the short name.
  ("Apache 2.0", "Apache License\nVersion 2.0"),  // All capitalized-lowercase, version separated by newline. In short name, the version is shown as a floating-point number. Long name only adds "License" and "Version" to the short name
  ("Boost Software License 1.0", "Boost Software License - Version 1.0"),  // All capitalized-lowercase, version separated by a dash. Short name includes the word "License". Long name only adds "Version" to the short name.
  ("The Unlicense", "This is free and unencumbered software released into the public domain."),  // Completely different to others, although it makes more sense
];
```
This way, it is quite complicated to contribute to the licenses, and for either the user or someone reviewing the codebase, it may be complicated to interpret

**Describe the solution you'd like**
I recommend using the SPDX short identification for the short name of the licenses, and leaving the full license name in a capitalized-lowercase form as the long name.
Some cases of popular licenses, e.g. the GPLv3, are most known by another short name rather than the SPDX identifier, which in this case would be  GPL-3.0; in this case, keeping the common name may be a good idea, although may leave to confusion of the common short name with the SPDX identifier. For more information on the SPDX names, you can find them on the [Open Source Initiative](https://opensource.org/licenses/alphabetical).
In the field of the long name, my opinion is that the best option is to leave it all straight, without dashes or newlines, but rather of the form _License Complete Name Version x.y_.

**Describe alternatives you've considered**
For the long name, there are other styles that may work out, for example, all lowercase or all uppercase.
For the short name, the SPDX identifier is the most known and widely accepted identifier, although they may be some others that I do not know about, in which case there could be other possibilities for the short name.

**Additional context**
**⚠️ Please, do not make any changes to the license before reading further**
I am currently editing the licenses, adding new ones and fixing others. So far I have edited the Boost License to the SPDX identifier, and added a few others found in the [Open Source Initiative website](https://opensource.org/licenses/alphabetical). If you take any decision on a naming standard, please do not modify the licenses (or at least not the Boost license). Allow me to submit a pull request first, or leave me the job of changing them, I'll be glad to do it!

**Comment by HipyCas** [comment]
I would also recommend sorting the licenses some way, for example in alphabetical order by long name, in order to make it more readable and easier to contribute.

**Comment by The-Noah** [comment]
Thank you, I realize it is a mess.

The second item is *not* the long name, but rather how a file is identified as what license. It's done by [comparing it to the start of the trimmed file](https://github.com/The-Noah/lsfp/blob/dbfa5a85cbb1d2b006a518574023b6094cba4478/src/file_detection.rs#L54). That's why some have a newline in them.

Feel free to fix the other licenses as well!

**Comment by HipyCas** [comment]
Ok, thanks for the information!

So to get the start of the trimmed file, I should run the code you linked to on that LICENSE file, right?

And for the short name, it will be a pleasure to change them to the SPDX identifier. I'll publish a pull request for you to see the results. About this, should I leave the GPL licenses how they are (GPLv3) or change them to their SPDX identifier too (GPL-3.0)?

**Comment by The-Noah** [comment]
For the trimmed file I just manually reviewed the LICENSE file but running the code against it isn't a bad idea.

As for the GPL licenses, I'm fine with it either way. To me GPLv3 is nicer to look at but GPL-3.0 makes more sense.

**Comment by HipyCas** [comment]
I'll try running the code against it now, and if I do not get it to work, I'll just do it manually (I'm new to Rust, so I may not be able to get it to work).

The GPL licenses also look better to me as GPLv3, but if we set the others to SPDX, I'm going to set that as the SPDX version too. Also, there is really no place to confusion, so I think it's better to go with an standard version

I'm going to get to work on it now, hope i get you a PR soon!

**Comment by The-Noah** [comment]
I'm new to Rust too, don't sweat it 🙂

Going with SPDX for everything sounds good :+1:

**Comment by HipyCas** [comment]
Another issue that I found as I was adding new licenses, is that they do not follow any specific order.
Should I order them in alphabetical order or any other order?

**Comment by The-Noah** [comment]
Alphabetical makes the most sense to me.
