### ISSUE TITLE
Unconsistent git hints thickness

### ISSUE THREAD

**Issue by HipyCas** [The-Noah/lsfp#32]
**Describe the bug**
When printing a git annotation (such as `[ M ]`), if the item that it is printed next to is colourized, the first square bracket has kind of a thicker stroke.

**To Reproduce**
1. Go to a git repository
2. Ensure that there are files that will get colour
3. Modify those files
4. Run lsfp and see error

**Expected behavior**
The two possibilities that are see are the following: making it normal thickness, as the closing square bracket; or making both brackets or the full annotation thicker, consistent with the first square bracket.

**Screenshots**
![Screenshot from 2021-04-11 20-00-08](https://user-images.githubusercontent.com/54776315/114316063-2a7ce480-9b02-11eb-8bf5-5c250644a965.png)

**Additional context**
I have previously done my testing on a Windows 10 machine, but recently I moved away from windows into a Linux laptop (Pop!_OS), therefore this output is, at least, obtained in Linux/Debian/Ubuntu/Pop!_OS. I am currently using Fira Code Nerd font and Tilix.

**Comment by The-Noah** [comment]
Thanks for the spot! Both brackets should be normal thickness, if you'd like to tackle the issue.

**Comment by The-Noah** [comment]
Possibly fixed this in f9efb0219f18931b92e85b64c3b5b5e8aa384e85, let me know if it's now correct.

**Comment by HipyCas** [comment]
Works perfectly now! :smile:
