### ISSUE TITLE
Replace is_ok() and is_err() by match

### ISSUE THREAD

**Issue by HipyCas** [The-Noah/lsfp#36]
In src/main.rs, were reading the directories inside the main function, there is an `if`/`else` clause that could be simplified with a `match` clause. This change also contribute to issue #20 and can also fall in the `dx` category.
**I can implement the code discussed in this issue, or other proposals that you may have, and fix the error codes in the following couple days if that works for you**

### Current code

The current code is as follows, starting at line 160 and expanding up to line 176:

```rust
let read_dir = fs::read_dir(path_to_scan);
if read_dir.is_ok() {
      // do stuff with read_dir...
} else if read_dir.is_err() {
      // raise error
}
```

This code uses more lines and characters, with an additional variable, and can be simplified and reduced as shown below.

### Proposed code

The proposition is to change the `if`/`else` clause by a `match` clause as follows:

```rust
match fs::read_dir(path_to_scan) {
      Ok(contents) => { /* do stuff with result... */ },
      Err(_) => { /* raise error */ }
}
```

This saves up some lines, gets rid of the `let read_dir` statement, deletes a now not needed call to `.unwrap()` and is probably a safer approach too.

### About exit codes

When an error is risen while reading the directory, the process exits with code 0, which in Unix systems, and basically all nowadays, means success. The error code should be changed to a more appropriate non-zero exit (error) code, if possible related to the issue, but at least to 1. By running lsfp on non-existing files, I have also noticed that it exits as success (exit code 0). 

A good place to start finding suitable exit codes could be [BSD's sysexit list](https://www.freebsd.org/cgi/man.cgi?query=sysexits&apropos=0&sektion=0&manpath=FreeBSD+11.2-stable&arch=default&format=html), but I can and will do some more research on exit codes. If non suitable codes are found, choosing our owns and writing some reference is also a possibility.

**Comment by The-Noah** [comment]
Thanks for the spot. I'm working on cleaning up error handling and using proper exit codes.

**Comment by HipyCas** [comment]
The provided fix to the problem does work, yet it is not great for user experience.

The problem with the `.expect("[...]")` syntax is that, when reached, the output is not user-friendly and not polished at all. Here you can see an output when trying to access `/dev/null` on Linux (release build):

![Screenshot from 2021-04-13 17-00-59](https://user-images.githubusercontent.com/54776315/114575235-41464700-9c7a-11eb-8c2b-9c1db7df02ac.png)

**Suggestion** (and what I usually do)

I would suggest creating a `die` (or similar name) function, that will be called when a critical error like the one shown before happens. I got this idea from a C tutorial I watched a while ago, and the strong point of doing this is that you can implement the same formatting to all error messages while accepting a custom error message for context and possibly an error code.
