### ISSUE TITLE
Config not shown in help and hard to understand .lsfprc

### ISSUE THREAD

**Issue by HipyCas** [The-Noah/lsfp#37]
**Describe the bug**
The config options mentioned in issue #18 and added in commit 162f45ecf774d04ec57438616aa277c71e1a643d do not appear in the configuration, making it impossible to use if you haven't dived into the issues or commits of this repository, as they are not mentioned in other any place either.

Another issue related to this is the .lsfprc file. The file is truly hard to understand, and it is basically impossible to write by hand. It does not follow any specific convention and repeats the `- config: ` part twice, apart from the fact that all `.*rc` files are for config, so there is really no reason to put that part, as far as I understand not looking at the code.

**To Reproduce**
If you are interested in seeing how the flag does not appear in help, just open help by running `lsfp --help` or `lsfp -h`.

For checking the .lsfprc file syntax, run `lsfp --config-git=false` and `lsfp --config-color=false` and open the .lsfprc file. You should see the syntax and repetition mentioned above.

**Expected behavior**
Regarding the help message, simply adding it to help, either as `--config-<feature>=<true/false> [explanatory text[` or each one individually.

About the .lsfprc file, I would recommend following some convention, for example JSON, but it may be a bit too overkilling for just two lines at the maximum. Therefore, I just recommend putting it as `git=false` and same for color, as it is simple enough to understand for everyone and can easily be hand-written.

**Comment by The-Noah** [comment]
I'll throw in my (somewhat) fancy config parser from another project that uses the `abc=def`.

**Comment by The-Noah** [comment]
Fixed in 047fb4bd83319ff3af2295ec460c8b02be29ec49 and 988527ffe22077326bced25f4a6ff43032199743.
