### ISSUE TITLE
Use dircolors in Linux (and maybe MacOS?)

### ISSUE THREAD

**Issue by HipyCas** [The-Noah/lsfp#38]
### About dircolors

Linux provides file color association for their `ls` command with a tool called `dircolors`. By default, Linux systems use this associations to colorise items when running `ls`. The advantage of this tool is that you can actually provide custom associations to the list, and therefore use custom colors. 

### Regarding MacOS

I do not really know if MacOS has this functionality, I was just supposing as it shares the use of the Bash shell and some underlying architecture, between others. I do not own a Mac to test on, so I am completely guessing this, I may be completely wrong!

### Color customization

This is not the most important part as far as I believe, but by using this tool we are actually giving the user an effective way to change the color associations in lsfp. We already provide our custom color associations, but letting the user have a choice could be a good idea. But with this, I would better allow to customize the colors in the `.lsfprc` file than using this, as it would also work for Windows and other OS's rather than just for Linux and relatives.

### Fill missing colors

I think this is where `dircolors` could shine in this project. While we don't complete the full color list, I think we can use this tool for, at leas in Linux systems, auto complete the list for now. I would keep this until we complete the color list, or even later, just in case there's some file type we didn't consider or a new one comes up, who knows!

### About a user-level configuration

I think it would be a good idea to allow the user to put a `.lsfprc` file in their home directory for user-wide configuration. This file would be just the same as a directory-specific one (in syntax and logic means), but it would have less preference than directory-specific ones. Regarding colors, they are something that does not make much sense to have customized at directory-level, so maybe just a JSON/YAML/TOML file at user-level would work.

**I'll be happy to implement this \`dircolors` functionallity, and if you want the user-level configuration when @The-Noah drops the parser in :smiley:**

**Comment by The-Noah** [comment]
I think it'd be better if we just fill in a lot more colors and make it configurable. Making a call to another program would reduce performance, which I'd say is more important than fully colored output.

**Comment by HipyCas** [comment]
Yes, you are absolutely right, performance could be a problem. I still think the idea of color customization and a user-level configuration file should be worked on, so I will close this issue and fill a new one regarding those points.
