### ISSUE TITLE
panic: Unable to get file extension

### ISSUE THREAD

**Issue by HipyCas** [The-Noah/lsfp#40]
**Describe the bug**
When running `lsfp` against some directories, it simply panics saying that it was unable to load the file extension. It does not give any context about what file it panics at, so I can't really give any more information.

**To Reproduce**
The reproduction of this error is mostly trial and error, as I have not identified when this happens. Sometimes, it even only happens when running with the `-a` flag, i.e. when listing all items. So, to reproduce, go search around some directories and try running `lsfp` or `lsfp -a`

**Expected behavior**
It should simply just work and not output that error. My bet is that it happens when trying to detect the extension to apply color to the output.

**Screenshots**
First example, with both output from `lsfp -a` and `ls -a`:
![Screenshot from 2021-04-24 13-05-21](https://user-images.githubusercontent.com/54776315/117972933-080dff00-b32c-11eb-8329-fcbe819041d6.png)
![Screenshot from 2021-04-24 13-05-49](https://user-images.githubusercontent.com/54776315/117972943-0a705900-b32c-11eb-8d1d-44aa4dc563dc.png)

This next one happens when running against my home directory, but weird enough the following one is what happened with the binary built one commit before:
![Screenshot from 2021-05-08 13-39-22](https://user-images.githubusercontent.com/54776315/117973195-5de2a700-b32c-11eb-9909-976174cddf6f.png)
![Screenshot from 2021-05-12 14-00-17](https://user-images.githubusercontent.com/54776315/117973178-58855c80-b32c-11eb-96dd-4c62ad43c614.png)

Lastly, here go two with _RUST_BACKTRACE=1_ (on a different directory) and a comparison of `lsfp`, `lsfp -a` and `ls -a` in the same directory:
![Screenshot from 2021-05-12 14-10-47](https://user-images.githubusercontent.com/54776315/117973355-97b3ad80-b32c-11eb-8a91-8f2a97e16e80.png)
![Screenshot from 2021-05-12 14-04-28](https://user-images.githubusercontent.com/54776315/117973864-2f190080-b32d-11eb-87ec-90fd368c3f6c.png)

If you are interested, I can provide more examples and some runs with _RUST_BACKTRACE=full_, even though it doesn't make much difference to _RUST_BACKTRACE=1_.

**Additional context**
This has a something to be with one issue that I raised on issue #36, which is the use of `.expect(...)` instead of proper error handling. I am currently working on a simple expect-like implementation more human friendly. I will put up a pull request soon with it.

**Comment by The-Noah** [comment]
Fixed in 7d51832c9084c56fc3a143e24415e29d07867147.

According to the [Rust docs for `Path`](https://doc.rust-lang.org/std/path/struct.Path.html#method.extension) `extension` will return `None` "if the file name begins with . and has no other .s within" which was causing it to fail on dot files.
