### ISSUE TITLE
Unclear difference between lsfp and lsfp-lite for windows

### ISSUE THREAD

**Issue by HipyCas** [The-Noah/lsfp#43]
Since a while ago, in the releases, two versions are published for windows when a new one is created. I guess that the lite version is with all features disabled, but I may be wrong and most people who don't have any knowledge of rust definitely won't understand the difference. I just propose adding a little section explaining this difference in the README.md (or maybe in a discussion?).

**Comment by The-Noah** [comment]
I've added the below to be right above the assets section, so when a user goes to download a binary they can see which each one is.

![image](https://user-images.githubusercontent.com/35819660/118031138-ce3cf880-b32b-11eb-83b4-72802fcdbd03.png)

**Comment by HipyCas** [comment]
Looks perfect!
