### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by HipyCas** [The-Noah/lsfp#47]
I have always wanted a `ls` tool that had icons, as it makes it more visual and also more pretty. As probably most people do, I changed my bash prompt, in my case to use [Starship](https://starship.rs), which required me to install a [Nerd Font](https://www.nerdfonts.com), as many other software now requires, e.g. powerline or icons for vim. This fonts are normal fonts, but that come with many icons as unicode characters.

So, I started playing with it, and I though of integrating it into lsfp. And so I did. The integration is fairly easy and just a a couple (literally) functions need to be changed. Here are some screenshots of what I achieved (added a space at the beginning to better visualize the icons):

![Screenshot from 2021-05-15 19-48-26](https://user-images.githubusercontent.com/54776315/118395434-c098b300-b64a-11eb-97a1-d2ead441b0c0.png)
![Screenshot from 2021-05-15 19-47-55](https://user-images.githubusercontent.com/54776315/118395435-c2fb0d00-b64a-11eb-8490-d2ab8c1af102.png)
![Screenshot from 2021-05-16 13-35-38](https://user-images.githubusercontent.com/54776315/118395654-cd69d680-b64b-11eb-8876-a83f5038ff51.png)
![Screenshot from 2021-05-16 13-36-47](https://user-images.githubusercontent.com/54776315/118395657-d064c700-b64b-11eb-9ee3-fa5f420867aa.png)
![Screenshot from 2021-05-16 13-43-34](https://user-images.githubusercontent.com/54776315/118395832-c5f6fd00-b64c-11eb-864f-b46149ba59b3.png)

I picked up these specific icons because I thought that they fitted the best and where the easiest to see (still not perfect, I have to look over some more), but there are many alternatives for each unique icon, and can all be found at the [Nerd Font cheatsheet](https://www.nerdfonts.com/cheat-sheet). As you can see, I also added a generic open folder for directories and a generic file icon for files whose extension is not yet registered. I would also like to know if you think that it would be a good idea to change the open folder icon for a closed folder one for collapsed directories? It would look something like this:

![Screenshot from 2021-05-16 13-59-01](https://user-images.githubusercontent.com/54776315/118396246-f2ac1400-b64e-11eb-9fc6-da343a15bfef.png)

Because there probably are many people that don't have a Nerd Font in use, we could make this feature an opt-in rather than opt-out, so not showing them by default, but rather create a new flag (`-i` and `--icon/s`) to show them if present.

Waiting to see what you think of it! I have most of the changes done, so I just have to finish some details and push if you tell me to go ahead!

**Comment by The-Noah** [comment]
This looks awesome!

- I like the collapsed directories having a different icon. 
- To me it makes more sense if it was a config variable rather than a flag, as you probably always want it or never want it.
- I wonder if it's possible to detect if the font is installed, that way it can automatically be enabled.

**Comment by HipyCas** [comment]
I am glad you like it!

I though of a flag because is the simplest way tom implement it, but probably it would be great to set it in a config file. Maybe, we could add a simple serde parser for a user level TOML file, that could be in the users directory, like `/home/someuser/.lsfp.toml` or `/home/someuser/.lsfprc/`. I just said TOML because it is often used for configuration files and is what rust uses, but any other format could work.

I have been trying to search around how to get the user font, but I have not yet found any good option. One of the problems is that each software uses their font, e.g. vscode does not uses the same font as my terminal emulator for the integrated terminal. I have come across some ways of getting the font, but they are mostly system wide, although I guess that's better than nothing. I will keep searching anyway!

I will then get the code ready for a pull request making use of the flag mentioned above, and then work on the configuration, does that make sense to you?

And just a couple questions before finishing it:

- Should I put an space before the items as I did or just take that testing space out? I guess it makes more sense not to have the space.
- I added a third item in the `FILE_EXTENSION_COLORS` constant, for holding the icon, and used the already existing `file_detection::file_extension_color` functionto get it. Does that look fine to you?

**Comment by The-Noah** [comment]
> Should I put an space before the items as I did or just take that testing space out? I guess it makes more sense not to have the space.

I like the space, makes it easier to read.

---

> I added a third item in the `FILE_EXTENSION_COLORS` constant, for holding the icon, and used the already existing `file_detection::file_extension_color` functionto get it. Does that look fine to you?

Yep :+1:

---

> And should the closed icon for collapsed directories apply even if not in tree view?

I think it'd be good to completely removed the separate indication when not in tree view, since it doesn't apply. So no don't do the closed icon when not in tree.
