### ISSUE TITLE
Collapsed directories looking uncollapsed with `-a` flag

### ISSUE THREAD

**Issue by HipyCas** [The-Noah/lsfp#48]
Working on the icons, I have come across this (in `print_item(...)`):

```rust
if path.is_file() {
  /* ... */
} else if !flags.all && constants::COLLAPSED_DIRECTORIES.contains(&item_name) {
  name_prefix = String::new().underline(flags);
}
```

This makes collapsed folders show as so when the software is run withot the `-a` flag. The problem I see is that, when running `lsfp -a`, collapsed directories like _node_modules_ appear as if they were not. I think this should only happen when you run it with the `-t` flag, so the output is as following:

- `lsfp` -> underlined collapsed directories
- `lsfp -a` -> underlined collapsed directories
- `lsfp -t` -> underlined closed collapsed directories
- `lsfp -a -t` -> normal open collapsed directories

I have tried to change this, and I have come with the solution, which is changing the `else if` to teh following:

```rust
/* ... */
} else if !(flags.all && flags.tree) && constants::COLLAPSED_DIRECTORIES.contains(&item_name) {
/* ... */
```

**Comment by The-Noah** [comment]
LGTM

**Comment by HipyCas** [comment]
I have done some changes to the code,  and this is what I came up with:

- `lsfp`
  ![Screenshot from 2021-05-17 12-29-10](https://user-images.githubusercontent.com/54776315/118474873-d621e180-b70b-11eb-8b6b-348fe462034a.png)
- `lsfp -t`
  ![Screenshot from 2021-05-17 12-29-27](https://user-images.githubusercontent.com/54776315/118474916-e76aee00-b70b-11eb-9e7f-66891465eea0.png)
- `lsfp -a`
  ![Screenshot from 2021-05-17 12-29-51](https://user-images.githubusercontent.com/54776315/118474958-f5207380-b70b-11eb-8aaf-eafda6bf8019.png)
- `lsfp -a -t`
  ![Screenshot from 2021-05-17 12-30-08](https://user-images.githubusercontent.com/54776315/118475000-ffdb0880-b70b-11eb-9f7b-faff5c42745a.png)

Does the collapsed folders look good to you that way or you would like it other way? I am also setting the same "rule" for the underline and the icon mentioned in #47, I think that's the best way to go right?

**Comment by The-Noah** [comment]
Yep looks good!
