### ISSUE TITLE
Listing when setting config

### ISSUE THREAD

**Issue by HipyCas** [The-Noah/lsfp#51]
**Is your feature request related to a problem? Please describe.**
With the new config update, when trying out, I found out that it prints the new setting, but it still lists the directory. This is probably not needed, as you really just want to set the configuration, and could even be an undesired behaviour in some cases, e.g. in scripts.  This also applies for when getting the value, e.g. in a script the config output would be really easy to pass if the program didn't list the full directory.

**Describe the solution you'd like**
I think that when it detects that it is being passed a config flag, it should just print the first line that says about it, `set <config>=<value>`, and exit with code 0 not printing any more content.

**Comment by HipyCas** [comment]
This is not about this specific issue, but about the milestones. I noticed that you started adding issues to the v0.6 milestone. So, I have to small changes that are mostly fixes, one is finishing issue #48 and other has to be with commit e55a2efdb30ea7b4b742679c7227b296814e3442, should I push them and then get v0.5.0 out?

**Comment by The-Noah** [comment]
Yeah, v0.5 is aiming to bring a lot of stability and bug fixes while v0.6 will focus on improving the user experience.

**Comment by HipyCas** [comment]
Ok. I'll test lsfp a bit more to see if I can find any issues and fix them. On the other hand I will start working on some v0.6 features like icons. Shouldn't this issue actually go into v0.5, as it is a simple fix/improvement?

**Comment by The-Noah** [comment]
It's not really fixing a bug or improving stability, just improving how the user uses it. You can still work on v0.6 before v0.5 is released, it's not a strict "one version at a time" workflow.
