### ISSUE TITLE
`args_to_remove` optimization

### ISSUE THREAD

**Issue by HipyCas** [The-Noah/lsfp#61]
Working on the `args::get` function, I looked at how the `args_to_remove` Vector is created, and thought that there may be a better way to do it. As far as I am concerned, allocating a Vector that can grow in size takes more memory space and consumption that allocating a fixed size one. Therefore, the code could be _really slightly_ improved by creating a vector with the capacity of the number of arguments, as in no case more than arguments are would be removed. Doing this is as simple as: `Vec::with_capacity(args.len())`. I can do it in a quick PR soon or already include it in the chainable flags PR, as you wish (created an issue just to remember that it can be done).

**Comment by The-Noah** [comment]
Nice! Either PR is fine.
